baseURL: https://aafu.pages.dev/
languageCode: en-us
build:
  writeStats: true
params:
  title: isaac-ahlgren.github.io
  author: Darshan Baral
  description: Website title
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Cloudflare](https://www.cloudflare.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Isaac Ahlgren"
    tagline: Graduate Student
    contact: iahlgren@luc.edu
    location: "Loyola University Chicago"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/isaac-ahlgren123/"
        title: LinkedIn
      #- icon: fab fa-stack-overflow
      #  url: "#"
      #  title: StackOverflow
      - icon: fab fa-github
        url: "https://github.com/isaac-ahlgren"
        title: GitHub
      #- icon: fab fa-twitter
      #  url: "#"
      #  title: Twitter
      #- icon: fab fa-orcid
      #  url: "#"
      #  title: Orcid
      - icon: ai ai-google-scholar
        url: "https://scholar.google.com/citations?user=dZawE3MAAAAJ&hl=en"
        title: Google Scholar
      #- icon: fab fa-researchgate
      #  url: "#"
      #  title: ResearchGate
  showInAccordion:
    - item: aboutme
      expand: true
    - item: publication
    - item: experience
  aboutme:
    title: About Me
    icon: fas fa-user
    description: |
      I am a lead graduate student for the Software and Systems Laboratory (SSL) at Loyola University Chicago.
      Currently finishing up a Masters in Computer Science at Loyola University Chicago and looking to apply to PhD schools in the upcoming cycle. 

      My research interests have broadly revolved around privacy and security for software and systems. But, I am particularly interested in the **security and privacy of embedded systems, Internet of Things, Cyber-Physical systems, and hardware security**.
      My work currently has to do with developing scalable authentication systems for IoT devices.
    edu_list:
      - degree: MS in Computer Science
        college: Loyola University Chicago
        dates: 2023 - Present
      - degree: B.S. in Computer Science
        college: Loyola University Chicago
        dates: 2019 - 2023
  publication:
    title: Publications
    icon: fas fa-book
    format:
      - title
      - authors
      - journal
      - date
    types:
      - Journal Articles
      - Proceedings
    list:
      - title: >-
          A Signal Injection Attack Against Zero Involvement Pairing and Authentication for the Internet of Things 
        authors: "Isaac Ahlgren, Jack West, Kyuin Lee, George Thiruvathukal, and Neil Klingensmith"
        date: "2024"
        journal: "Workshop On Design Automation For CPS and IoT (DESTION 2024)"
        url: "#"
      - title: >-
          â€Establishing Trust in Vehicle-to-Vehicle Coordination: A Sensor Fusion Approach 
        authors: "J. Veselsky, J West, Isaac Ahlgren, et a"
        date: "2022"
        journal: "Workshop on Data-Driven and Intelligent Cyber-Physical Systems for Smart Cities Workshop (DI-CPS)"
        url: "https://doi.org/10.1145/3508396.3517075"
      - title: >-
          Poster: Userland Containers for Mobile Systems
        authors: "Isaac Ahlgren, Victor Rakotondranoro, Yasin N. Silva, Eric Chan-Tin, George K. Thiruvathukal,
and Neil Klingensmith"
        date: "2023"
        journal: "Workshop on Mobile Computing Systems and Applications (HotMobile)"
        url: "https://doi.org/10.1145/3572864.3581588"
      - title: >-
          Poster: A universally composable bit generation scheme for zero involvement authentication
        authors: "Isaac Ahlgren, Jack West, George K. Thiruvathukal, and Neil Klingensmith"
        date: "2022"
        journal: "Workshop on Mobile Computing Systems and Applications (HotMobile)"
        url: "https://doi.org/10.1145/3508396.3517076"
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Graduate Research Assistant
        dates: 2023 - *Present*
        company: Loyola University Chicago
        details: |1-
          - Lead graduate student in the Software and Systems Laboratory who mentored four students on a large scale project. The mentorship was awarded with the Graduate Research Mentorship Award.
          - Developed a cluster of research IoT authentication systems using custom PCBs and Raspberry Pis connected to a variety of sensors. Software was written in Python and C where each system uses Avahi, OpenVPN, and Ansible to automatically set up communication between devices.
          - Worked within the Linux kernel to research virtualization techniques for mitigating container escape security vulnerabilities in technologies like Docker.
          - Worked with ESP32 and NORA-B1 microcontrollers to modify wireless communication protocols like WiFi or Bluetooth.
          - Helped instruct Computer Systems and Operating Systems classes.
      - position: Embedded Software Engineer Intern
        dates: May 2021 - August 2021
        company: Motorola Solutions
        details: |1-
          - Researched and modeled an radio frequency anomaly detection algorithm in Python.
          - Developed anomaly detection system with a software-defined radio.
          - Thoroughly documented approaches to the algorithm as well as future possible approaches to the algorithm.
